# - means comment, this line will be ignored by kubernetes

# - we can use .yaml or .yml as extension for files

# key values
key: value
name: ravi
city: hyderabad

# collection of data as a set of key-value pairs 
# dictionary
trainer:
  name: ravi
  city: hyderabad
  state: telangana
  country: india

# Represent mutiple items using Lists
# list
courses:
- aws
- azure
- devops
- python