# generate a deployment with nginx pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.values.deployment.name}}
spec:
  replicas: {{.values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.values.deployment.appLabel}}
  template:
    metadata:
      labels:
        app: {{.values.deployment.appLabel}}
    spec:
      containers:
      - name: {{.values.deployment.containerName}}
        image: {{.values.deployment.image}}
        ports:
        - containerPort: {{.values.deployment.containerPort}}
