# Generate nginx service
apiVersion: v1
kind: {{.values.service.kind}}
metadata:
  name: {{.values.service.name}}
spec:
  type: {{.values.service.type}}
  selector:
      app: {{.values.deployment.appLabel}}
  ports:
      - protocol: TCP
        port: {{.values.service.port}}
        targetPort: {{.values.deployment.containerPort}}
        nodePort: {{.values.service.nodePort}}